#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path


def resolve_output_paths(runtime: dict, config: dict) -> dict:
    output_dir = Path(runtime['output_dir'])
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / runtime['report_filename']
    summary_json_path = output_dir / 'summary.json'
    media_manifest_path = output_dir / 'media-manifest.json'
    distribution_summary_path = output_dir / config['output'].get('distribution_summary_filename', 'distribution-summary.txt')
    return {
        'output_dir': str(output_dir),
        'report_path': str(report_path),
        'summary_json_path': str(summary_json_path),
        'media_manifest_path': str(media_manifest_path),
        'distribution_summary_path': str(distribution_summary_path),
    }


def render_markdown(report_items: list[dict], runtime: dict, config: dict) -> str:
    lines = []
    lines.append(f"# {runtime['title']}")
    lines.append('')
    lines.append(f"- Profile: `{runtime['profile_name']}`")
    lines.append(f"- Content window: `{runtime['content_date']}`")
    lines.append(f"- Output date: `{runtime['run_date']}`")
    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('## Core items')
    lines.append('')
    for item in report_items:
        lines.append(f"### {item['rank']}）{item['handle']} / {item['title']}")
        lines.append(f"- 信息源：`@{item['handle']}`")
        lines.append(f"- 互动：Likes {item['likes']} / Views {item['views']}")
        lines.append(f"- 链接：{item['url']}")
        lines.append(f"- 原文摘要：{str(item['raw_text']).replace(chr(10), ' ')[:220]}")
        lines.append(f"- 中文整理：{item['summary_zh']}")
        for f in item.get('embedded_media_files', []):
            rel = Path(f).resolve().relative_to(Path(runtime['output_dir']).resolve())
            lines.append(f"![[{rel.as_posix()}]]")
        lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('## Runtime notes')
    lines.append('- Generated by x-daily-report')
    lines.append('- Publish step is intentionally decoupled from report generation')
    return '\n'.join(lines) + '\n'


def build_distribution_summary(report_items: list[dict], runtime: dict, config: dict, report_path: str) -> str:
    lines = [f"【{runtime['title']}】"]
    for idx, item in enumerate(report_items[:5], 1):
        media_count = len([f for f in item.get('media_files', []) if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp'))])
        lines.append(f"{idx}. @{item['handle']} {item['url']} 媒体{media_count}")
    lines.append(f"Report：{report_path}")
    return '\n'.join(lines) + '\n'
